const builds = [
  {
    id: "3060-ti",
    tier: "Performance Tier",
    name: "RTX 3060 Ti Gaming Build",
    image: "images/build-1.jpeg",
    images: [
      "images/build-1.jpeg",
      "images/build-1-side.jpeg",
      "images/build-1-front.jpg",
      "images/build-1-inside.jpg",
    ],
    status: "in-stock", // "Sold"
    price: "$850",
    fps: "120 FPS @ 1440P",
    youtube: "https://www.youtube.com/watch?v=YOUR_VIDEO_ID",
    specs: {
      cpu: "i7-9700K",
      gpu: "RTX 3060 Ti",
      motherboard: "MSI Z390 Gaming Plus",
      memory: "16GB DDR4",
      storage: "1TB NVMe SSD",
      cooling: "Corsair AIO",
      psu: "Thermaltake 650W PSU",
      case: "SAMA V40",
    },
    games: [
      "Fortnite at 85 FPS Performance Mode",
      "Battlefield 6 at 80 FPS Performance Mode",
    ],
  },
  {
    id: "gtx-1660-super",
    tier: "Budget Tier",
    name: "Starter Gaming PC",
    image: "images/build-2.jpg",
    images: [
      "images/build-2.jpg",
      "images/build-2-side.jpg",
      "images/build-2-front.jpg",
      "images/build-2-inside.jpg",
    ],
    status: "sold",
    price: "$550",
    fps: "90 FPS @ 1080p",
    // youtube: "",
    specs: {
      cpu: "i5-7600K",
      gpu: "GTX 1660 Super",
      motherboard: "ASUS Z170-A",
      memory: "16GB DDR4",
      storage: "500GB SSD",
      cooling: "Air Cooler",
      psu: "600W PSU",
      case: "NZXT Case",
    },
    games: ["Fortnite at 120 FPS", "Apex Legends at 75 FPS"],
  },
  {
    id: "rtx-3070-performance",
    tier: "Higher-End Tier",
    name: "RTX 3070 Performance Build",
    image: "images/build-3.jpg",
    images: [
      "images/build-3.jpg",
      "images/build-3-side.jpg",
      "images/build-3-front.jpg",
      "images/build-3-inside.jpg",
    ],
    status: "sold",
    price: "$950",
    fps: "140 FPS @ 4K",
    // youtube: "",
    specs: {
      cpu: "Ryzen 7 5800X",
      gpu: "RTX 3070",
      motherboard: "MSI B550 Tomahawk",
      memory: "32GB DDR4",
      storage: "1TB NVMe SSD",
      cooling: "240mm AIO",
      psu: "750W PSU",
      case: "Lian Li Case",
    },
    games: ["Warzone at 120 FPS", "Cyberpunk at 80 FPS High"],
  },
];
